version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - npm run coverage
      - echo Build completed on `date`git pu
artifacts:
  files:
    - coverage*/**
  discard-paths: yes
